// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 日志数据结构
 */
export type AppLog = { id: bigint, level: string, message: string, target: string | null, created_at: string, };
