// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metadata = { title: string | null, artist: string | null, album: string | null, duration: number, bitrate: number | null, sample_rate: number | null, channels: number | null, cover: string | null, };
