// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 播放历史数据结构
 */
export type PlayHistory = { id: bigint, path: string, played_at: string, duration: bigint | null, completed: number | null, title: string | null, artist: string | null, album: string | null, };
