// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackState } from "./PlaybackState";

export type PlayerState = { state: PlaybackState, current_path: string | null, volume: number, position: number, duration: number | null, };
