// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Song } from "./Song";

export type ScanResult = { normal_songs: Array<Song>, encrypted_songs: Array<Song>, metadata_errors: Array<string>, };
