// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 歌曲数据结构
 */
export type Song = { id: string, title: string, artist: string, album: string, duration: number, path: string, cover: string | null, play_count: number, created_at: string, is_liked: boolean | null, };
